# Generated by Django 4.1.5 on 2023-02-17 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usercategory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beneficiarymodel',
            options={'verbose_name': ('1: Beneficiary',), 'verbose_name_plural': ('1: Beneficiary',)},
        ),
    ]
