# Generated by Django 4.1.5 on 2023-02-01 05:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans_application', '0035_remove_tbl_app_nectadetails_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblDisability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': '4: TBL Disability',
                'verbose_name_plural': '4: TBL Disability',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TblPreliminaryInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicantDisable', models.BooleanField()),
                ('fatherAlive', models.BooleanField(default=1)),
                ('motherAlive', models.BooleanField(default=1)),
                ('resitFormFour', models.IntegerField(default=1, max_length=1)),
                ('formSixOrDiploma', models.IntegerField(default=1, max_length=1)),
                ('fatherDisable', models.BooleanField(default=0)),
                ('motherDisable', models.BooleanField(default=0)),
                ('tasafSponsored', models.BooleanField(default=0)),
                ('hasGuardian', models.BooleanField(default=0)),
                ('appYear', models.CharField(max_length=4)),
                ('confirm', models.BooleanField(default=0)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tbl_preliminary_applicant', to='loans_application.tbl_app_applicant')),
            ],
        ),
        migrations.CreateModel(
            name='TblTasafInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=40)),
                ('middleName', models.CharField(max_length=40)),
                ('lastName', models.CharField(max_length=40)),
                ('dateOfBirth', models.DateField()),
                ('registrationNo', models.CharField(max_length=30)),
                ('memberLineNo', models.IntegerField(max_length=2)),
                ('gender', models.CharField(max_length=10)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('preliminary', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tbl_tasaf_preliminary', to='preliminary_info.tblpreliminaryinfo')),
            ],
        ),
        migrations.CreateModel(
            name='TblParentsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=40)),
                ('middleName', models.CharField(max_length=40)),
                ('lastName', models.CharField(max_length=40)),
                ('occupation', models.CharField(max_length=50)),
                ('postalAddress', models.CharField(max_length=50)),
                ('physicalAddress', models.CharField(max_length=50)),
                ('mobileNumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('gender', models.CharField(max_length=1)),
                ('applicantRelationship', models.CharField(max_length=20)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('preliminary', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tbl_parent_preliminary', to='preliminary_info.tblpreliminaryinfo')),
            ],
        ),
        migrations.CreateModel(
            name='TblParentDeathInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deathCertificateNo', models.CharField(max_length=40)),
                ('deceasedName', models.CharField(max_length=60)),
                ('applicantRelationship', models.CharField(max_length=20)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('preliminary', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tbl_parentsDeathInfo_preliminary', to='preliminary_info.tblpreliminaryinfo')),
            ],
        ),
        migrations.CreateModel(
            name='TblOtherFormFourNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otherFormFourIndexNo', models.CharField(max_length=16)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('preliminary', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tbl_otherform4Indexn_preliminary', to='preliminary_info.tblpreliminaryinfo')),
            ],
        ),
        migrations.CreateModel(
            name='TblDisabilityInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disabledPerson', models.CharField(max_length=20)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('disabilityType', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tbl_disabilityInfo_disability', to='preliminary_info.tbldisability')),
                ('preliminary', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tbl_disabilityInfo_preliminary', to='preliminary_info.tblpreliminaryinfo')),
            ],
        ),
    ]
