# Generated by Django 4.1.5 on 2023-02-22 08:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applicantProfile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblDisability',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': '4: TBL Disability',
                'verbose_name_plural': '4: TBL Disability',
                'db_table': 'tbl_disability',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TblPreliminaryInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('applicantDisable', models.BooleanField()),
                ('fatherAlive', models.BooleanField(default=1)),
                ('motherAlive', models.BooleanField(default=1)),
                ('resitFormFour', models.IntegerField(default=1)),
                ('formSixOrDiploma', models.IntegerField(default=1)),
                ('fatherDisable', models.BooleanField(default=0)),
                ('motherDisable', models.BooleanField(default=0)),
                ('tasafSponsored', models.BooleanField(default=0)),
                ('hasGuardian', models.BooleanField(default=0)),
                ('appYear', models.CharField(max_length=4)),
                ('confirm', models.BooleanField(default=0)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tbl_preliminary_applicant', to='applicantProfile.tblappprofile')),
            ],
            options={
                'verbose_name': 'Tbl preliminary info',
                'verbose_name_plural': 'Tbl preliminary info',
                'db_table': 'tbl_preliminary_info',
            },
        ),
        migrations.CreateModel(
            name='TblTasafInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=40)),
                ('middleName', models.CharField(max_length=40)),
                ('lastName', models.CharField(max_length=40)),
                ('dateOfBirth', models.DateField()),
                ('registrationNo', models.CharField(max_length=30)),
                ('memberLineNo', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('preliminary', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tbl_tasaf_preliminary', to='preliminary_info.tblpreliminaryinfo')),
            ],
            options={
                'verbose_name': 'Tbl tasaf details',
                'verbose_name_plural': 'Tbl tasaf details',
                'db_table': 'tbl_tasaf_details',
            },
        ),
        migrations.CreateModel(
            name='TblParentsInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=40)),
                ('middleName', models.CharField(max_length=40)),
                ('lastName', models.CharField(max_length=40)),
                ('occupation', models.CharField(max_length=50)),
                ('postalAddress', models.CharField(max_length=50)),
                ('physicalAddress', models.CharField(max_length=50)),
                ('mobileNumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('gender', models.CharField(max_length=1)),
                ('applicantRelationship', models.CharField(max_length=20)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('preliminary', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tbl_parent_preliminary', to='preliminary_info.tblpreliminaryinfo')),
            ],
            options={
                'verbose_name': 'tbl Parents details',
                'verbose_name_plural': 'tbl Parents details',
                'db_table': 'tbl_parents_details',
            },
        ),
        migrations.CreateModel(
            name='TblParentDeathInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('deathCertificateNo', models.CharField(max_length=40)),
                ('deceasedName', models.CharField(max_length=60)),
                ('applicantRelationship', models.CharField(max_length=20)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('preliminary', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tbl_parentsDeathInfo_preliminary', to='preliminary_info.tblpreliminaryinfo')),
            ],
            options={
                'verbose_name': 'tbl Parent Death Details',
                'verbose_name_plural': 'tbl Parent Death Details',
                'db_table': 'tbl_parent_death_details',
            },
        ),
        migrations.CreateModel(
            name='TblOtherFormFourNumber',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('otherFormFourIndexNo', models.CharField(max_length=16)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('preliminary', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='TblOtherForm4Number_preliminary', to='preliminary_info.tblpreliminaryinfo')),
            ],
            options={
                'verbose_name': 'tbl other Form four Numbers',
                'verbose_name_plural': 'tbl other Form four Numbers',
                'db_table': 'tbl_other_form_four_index_numbers',
            },
        ),
        migrations.CreateModel(
            name='TblDisabilityInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('disabledPerson', models.CharField(max_length=20)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('disabilityType', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tbl_disabilityInfo_disability', to='preliminary_info.tbldisability')),
                ('preliminary', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tbl_disabilityInfo_preliminary', to='preliminary_info.tblpreliminaryinfo')),
            ],
            options={
                'verbose_name': 'tbl disability details',
                'verbose_name_plural': 'tbl disability details',
                'db_table': 'tbl_disability_details',
            },
        ),
    ]
