# Generated by Django 4.1.5 on 2023-02-28 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicantProfile', '0001_initial'),
        ('preliminary_info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbldisabilityinfo',
            name='preliminary',
        ),
        migrations.RemoveField(
            model_name='tblparentdeathinfo',
            name='preliminary',
        ),
        migrations.RemoveField(
            model_name='tblparentsinfo',
            name='preliminary',
        ),
        migrations.RemoveField(
            model_name='tbltasafinfo',
            name='preliminary',
        ),
        migrations.AddField(
            model_name='tbldisabilityinfo',
            name='app_year',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='tbldisabilityinfo',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tbl_disability_info_applicant', to='applicantProfile.tblappprofile'),
        ),
        migrations.AddField(
            model_name='tblparentdeathinfo',
            name='appYear',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='tblparentdeathinfo',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tbl_parent_death_applicant', to='applicantProfile.tblappprofile'),
        ),
        migrations.AddField(
            model_name='tblparentsinfo',
            name='appYear',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='tblparentsinfo',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tbl_parent_info_applicant', to='applicantProfile.tblappprofile'),
        ),
        migrations.AddField(
            model_name='tbltasafinfo',
            name='app_year',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='tbltasafinfo',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tbl_tasaf_info_applicant', to='applicantProfile.tblappprofile'),
        ),
        migrations.DeleteModel(
            name='TblOtherFormFourNumber',
        ),
    ]
