# Generated by Django 4.1.5 on 2023-03-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preliminary_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblparentsinfo',
            name='applicantRelationship',
            field=models.CharField(choices=[('FATHER', 'FATHER'), ('MOTHER', 'MOTHER')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tblparentsinfo',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=6),
        ),
    ]
