# Generated by Django 4.1.5 on 2023-02-01 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preliminary_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbltasafinfo',
            name='memberLineNo',
            field=models.IntegerField(),
        ),
    ]
