# Generated by Django 4.1.5 on 2023-02-23 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preliminary_info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbldisabilityinfo',
            name='preliminary',
        ),
        migrations.RemoveField(
            model_name='tblparentdeathinfo',
            name='preliminary',
        ),
        migrations.RemoveField(
            model_name='tblparentsinfo',
            name='preliminary',
        ),
        migrations.RemoveField(
            model_name='tbltasafinfo',
            name='preliminary',
        ),
    ]
