# Generated by Django 4.1.5 on 2023-03-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preliminary_info', '0002_alter_tblparentsinfo_applicantrelationship_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblparentsinfo',
            name='applicantRelationship',
            field=models.CharField(choices=[('Father', 'FATHER'), ('Mother', 'MOTHER')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tblparentsinfo',
            name='gender',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=6),
        ),
    ]
