# Generated by Django 4.1.5 on 2023-02-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preliminary_info', '0002_remove_tbldisabilityinfo_preliminary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbldisabilityinfo',
            name='appYear',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='tblparentdeathinfo',
            name='appYear',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='tblparentsinfo',
            name='appYear',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='tbltasafinfo',
            name='appYear',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
