# Generated by Django 4.1.5 on 2023-02-01 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preliminary_info', '0003_alter_tblpreliminaryinfo_formsixordiploma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblpreliminaryinfo',
            name='resitFormFour',
            field=models.IntegerField(default=1),
        ),
    ]
