# Generated by Django 4.1.5 on 2023-02-23 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preliminary_info', '0004_tbldisabilityinfo_applicant_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TblOtherFormFourNumber',
        ),
    ]
