# Generated by Django 4.1.5 on 2023-02-01 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preliminary_info', '0004_alter_tblpreliminaryinfo_resitformfour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblotherformfournumber',
            name='preliminary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='TblOtherForm4Number_preliminary', to='preliminary_info.tblpreliminaryinfo'),
        ),
    ]
