# Generated by Django 4.1.5 on 2023-02-19 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicantProfile', '0001_initial'),
        ('preliminary_info', '0008_alter_tblpreliminaryinfo_applicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblpreliminaryinfo',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tbl_preliminary_applicant', to='applicantProfile.tbl_app_profile'),
        ),
    ]
