# Generated by Django 4.1.5 on 2023-02-13 14:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans_application', '0047_alter_tbl_app_applicant_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TBL_Education_institution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('institute_type', models.CharField(choices=[('DIPLOMA', 'DIPLOMA'), ('HIGH_LEVEL_EDUCATION', 'HIGH LEVEL EDUCTION')], max_length=20, null=True)),
                ('institute_name', models.CharField(max_length=60, null=True)),
                ('instituteCode', models.CharField(max_length=15, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': '7: TBL Eduction Institute',
                'verbose_name_plural': '7: TBL Eduction Institute',
            },
        ),
        migrations.CreateModel(
            name='TblCourses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=50)),
                ('courseCode', models.CharField(max_length=30)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TblTertiaryEducationAwards',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('award', models.CharField(max_length=50)),
                ('regno', models.CharField(max_length=40)),
                ('entryYear', models.IntegerField()),
                ('graduateYear', models.IntegerField()),
                ('awardCategory', models.CharField(max_length=20)),
                ('gpa', models.FloatField()),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='TblAwardsInstitution', to='education_info.tbl_education_institution')),
            ],
        ),
        migrations.CreateModel(
            name='TblInstitutionCourse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='education_info.tblcourses')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='education_info.tbl_education_institution')),
            ],
        ),
        migrations.CreateModel(
            name='TBL_EducationInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('f4_no_of_seat', models.IntegerField(default=0)),
                ('pst4ed', models.CharField(max_length=30, null=True)),
                ('f4sps', models.CharField(max_length=30, null=True)),
                ('f4sps_cp', models.CharField(max_length=30, null=True)),
                ('f4sps_cp_phone', models.CharField(max_length=30, null=True)),
                ('f4sps_cp_addr', models.CharField(max_length=30, null=True)),
                ('pst4sps', models.CharField(max_length=30, null=True)),
                ('pst4sps_cp', models.CharField(max_length=30, null=True)),
                ('pst4sps_cp_phone', models.CharField(max_length=30, null=True)),
                ('pst4sps_cp_addr', models.CharField(max_length=30, null=True)),
                ('ay', models.CharField(max_length=30, null=True)),
                ('confirm', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ed_tbl_app_applicant', to='loans_application.tbl_app_applicant')),
            ],
            options={
                'verbose_name': '1: TBL Education',
                'verbose_name_plural': '1: TBL Education',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TBL_Education_FormSixInfos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('index_no', models.CharField(max_length=16)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ed_form6_info_tbl_app_applicant', to='loans_application.tbl_app_applicant')),
            ],
            options={
                'verbose_name': '4:TBL Eduction Form Six infos ',
                'verbose_name_plural': '4:TBL Eduction Form Six infos ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TBL_Education_FormFourInfos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('index_no', models.CharField(max_length=16)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ed_form4_info_tbl_app_applicant', to='loans_application.tbl_app_applicant')),
            ],
            options={
                'verbose_name': '3: TBL Eduction Form four infos ',
                'verbose_name_plural': '3: TBL Eduction Form four infos ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TBL_Education_ApplicantAttendedSchool',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('center_number', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('center_name', models.CharField(blank=True, max_length=10, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('necta_applicants', models.ManyToManyField(to='loans_application.tbl_app_nectadetails')),
            ],
            options={
                'verbose_name': '2: TBL Education Applicant Attended Schools',
                'verbose_name_plural': '2: TBL Education Applicant Attended Schools',
                'ordering': ['-created_at'],
            },
        ),
    ]
