# Generated by Django 4.1.5 on 2023-02-22 08:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans_application', '0050_delete_tbl_app_profile'),
        ('applicantProfile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institutions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('institutionName', models.CharField(db_column='institution_name', max_length=100)),
                ('institutionCode', models.CharField(db_column='institution_code', max_length=100)),
                ('geoLocated', models.BooleanField(blank=True, db_column='geo_located', default=False, null=True)),
                ('active', models.CharField(db_column='active', max_length=100)),
            ],
            options={
                'db_table': 'tbl_institutions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblCourses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=50)),
                ('courseCode', models.CharField(max_length=30)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': '8. TBL_COURSES',
                'verbose_name_plural': '8. TBL_COURSES',
                'db_table': 'tbl_courses',
            },
        ),
        migrations.CreateModel(
            name='TblDiplomaInstitutions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('institute_type', models.CharField(choices=[('DIPLOMA', 'DIPLOMA'), ('HIGH_LEVEL_EDUCATION', 'HIGH LEVEL EDUCTION')], max_length=20, null=True)),
                ('institute_name', models.CharField(max_length=60, null=True)),
                ('instituteCode', models.CharField(max_length=35, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': '7: TBL Eduction Institute',
                'verbose_name_plural': '7: TBL Eduction Institute',
                'db_table': 'tbl_diploma_institutions',
            },
        ),
        migrations.CreateModel(
            name='TblTertiaryEducationMasterAward',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('master_award', models.CharField(max_length=50)),
                ('regNo', models.CharField(max_length=40)),
                ('entryYear', models.IntegerField()),
                ('graduateYear', models.IntegerField()),
                ('gpa', models.FloatField()),
                ('app_year', models.CharField(max_length=4, null=True)),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='TblMasterAwards_Applicant', to='applicantProfile.tblappprofile')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='TblMasterAwardsInstitution', to='education_info.institutions')),
            ],
            options={
                'verbose_name': '10. Master Awards',
                'verbose_name_plural': '10. Master Awards',
                'db_table': 'tbl_tertiary_education_master_awards',
            },
        ),
        migrations.CreateModel(
            name='TblTertiaryEducationBachelorAwards',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('award', models.CharField(max_length=50)),
                ('regno', models.CharField(max_length=40)),
                ('entryYear', models.IntegerField()),
                ('graduateYear', models.IntegerField()),
                ('gpa', models.FloatField()),
                ('app_year', models.CharField(max_length=4, null=True)),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='TblAwards_TertiaryInfo', to='applicantProfile.tblappprofile')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='TblAwardsInstitution', to='education_info.institutions')),
            ],
            options={
                'verbose_name': '9. Tertiary Education Bachelor Award',
                'verbose_name_plural': '9. Tertiary Education Bachelor Award',
                'db_table': 'tbl_tertiary_education_bachelor_awards',
            },
        ),
        migrations.CreateModel(
            name='TblDiplomaDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('app_year', models.CharField(max_length=4, null=True)),
                ('avn', models.CharField(max_length=60, null=True)),
                ('entryYear', models.CharField(max_length=10, null=True)),
                ('graduateYear', models.CharField(max_length=10, null=True)),
                ('gpa', models.DecimalField(decimal_places=1, default=0.0, max_digits=1, null=True)),
                ('registrationNumber', models.CharField(max_length=60, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ed_diploma_info_tbl_app_applicant', to='applicantProfile.tblappprofile')),
                ('diplomaInstitution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ed_diploma_institution', to='education_info.tbldiplomainstitutions')),
            ],
            options={
                'verbose_name': '5:TBL Eduction Diploma infos ',
                'verbose_name_plural': '5:TBL Eduction Diploma infos ',
                'db_table': 'tbl_application_diploma_details',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TBL_EducationInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('f4_no_of_seat', models.IntegerField(default=0)),
                ('pst4ed', models.CharField(max_length=30, null=True)),
                ('f4sps', models.CharField(max_length=30, null=True)),
                ('f4sps_cp', models.CharField(max_length=30, null=True)),
                ('f4sps_cp_phone', models.CharField(max_length=30, null=True)),
                ('f4sps_cp_addr', models.CharField(max_length=30, null=True)),
                ('pst4sps', models.CharField(max_length=30, null=True)),
                ('pst4sps_cp', models.CharField(max_length=30, null=True)),
                ('pst4sps_cp_phone', models.CharField(max_length=30, null=True)),
                ('pst4sps_cp_addr', models.CharField(max_length=30, null=True)),
                ('ay', models.CharField(max_length=30, null=True)),
                ('confirm', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ed_tbl_app_applicant', to='applicantProfile.tblappprofile')),
            ],
            options={
                'verbose_name': '1: TBL Education',
                'verbose_name_plural': '1: TBL Education',
                'db_table': 'tbl_application_education_info',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TBL_Education_TertiaryEducationInfos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('admittedDegreeCategory', models.CharField(default='Master', max_length=15)),
                ('applicationYear', models.IntegerField(default='2023')),
                ('confirm', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('admittedCourse', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='education_info.tblcourses')),
                ('admittedInstitute', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='education_info.institutions')),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ed_te_info_tbl_app_applicant', to='applicantProfile.tblappprofile')),
            ],
            options={
                'verbose_name': '6:TBL Tertiary Education infos',
                'verbose_name_plural': '6:TBL Tertiary Education infos',
                'db_table': 'tbl_tertiary_education',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TBL_Education_FormSixInfos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('app_year', models.CharField(max_length=4, null=True)),
                ('f6index_no', models.CharField(max_length=16)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ed_form6_info_tbl_app_applicant', to='applicantProfile.tblappprofile')),
            ],
            options={
                'verbose_name': '4:TBL Eduction Form Six infos ',
                'verbose_name_plural': '4:TBL Eduction Form Six infos ',
                'db_table': 'tbl_application_form_six_details',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TBL_Education_FormFourInfos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('app_year', models.CharField(max_length=4, null=True)),
                ('second_seat_index_no', models.CharField(max_length=16, null=True)),
                ('third_seat_index_no', models.CharField(max_length=16, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ed_form4_info_tbl_app_applicant', to='applicantProfile.tblappprofile')),
            ],
            options={
                'verbose_name': '3: TBL Eduction Form four infos ',
                'verbose_name_plural': '3: TBL Eduction Form four infos ',
                'db_table': 'tbl_application_form_four_details',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TBL_Education_ApplicantAttendedSchool',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('center_number', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('center_name', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('necta_applicants', models.ManyToManyField(to='loans_application.tbl_app_nectadetails')),
            ],
            options={
                'verbose_name': '2: TBL Education Applicant Attended Schools',
                'verbose_name_plural': '2: TBL Education Applicant Attended Schools',
                'db_table': 'tbl_application_secondary_schools',
                'ordering': ['-created_at'],
            },
        ),
    ]
