# Generated by Django 4.1.5 on 2023-01-24 09:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loans_application', '0029_delete_tbl_app_applicantattendedschool'),
        ('education_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TBL_App_ApplicantAttendedSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_number', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('center_name', models.CharField(blank=True, max_length=10, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('necta_applicants', models.ManyToManyField(to='loans_application.tbl_app_nectadetails')),
            ],
            options={
                'verbose_name': '7:TBL App Applicant Attended Schools',
                'verbose_name_plural': '7:TBL App Applicant Attended Schools',
                'ordering': ['-created_at'],
            },
        ),
    ]
