# Generated by Django 4.1.5 on 2023-02-28 07:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('applicantProfile', '0001_initial'),
        ('education_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TBLEducationFormSixInfos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('app_year', models.CharField(max_length=4, null=True)),
                ('f6index_no', models.CharField(max_length=16)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ed_form6_info_tbl_app_applicant', to='applicantProfile.tblappprofile')),
            ],
            options={
                'verbose_name': '6:TBL Eduction Form Six infos ',
                'verbose_name_plural': '6:TBL Eduction Form Six infos ',
                'db_table': 'tbl_form_six_details',
                'ordering': ['-created_at'],
            },
        ),
    ]
