# Generated by Django 4.1.5 on 2023-02-21 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education_info', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TblInstitutionCourse',
        ),
    ]
