# Generated by Django 4.1.5 on 2023-02-15 07:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loans_application', '0047_alter_tbl_app_applicant_id_and_more'),
        ('education_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TBL_Education_TertiaryEducationInfos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('admittedDegreeCategory', models.CharField(default='Master', max_length=15)),
                ('applicationYear', models.IntegerField(default='2023')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('admittedCourse', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='education_info.tblcourses')),
                ('admittedInstitute', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='education_info.tbl_education_institution')),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ed_te_info_tbl_app_applicant', to='loans_application.tbl_app_applicant')),
            ],
            options={
                'verbose_name': '6:TBL Tertiary Education infos',
                'verbose_name_plural': '6:TBL Tertiary Education infos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TBL_Education_DiplomaInfos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ed_diploma_info_tbl_app_applicant', to='loans_application.tbl_app_applicant')),
            ],
            options={
                'verbose_name': '5:TBL Eduction Diploma infos ',
                'verbose_name_plural': '5:TBL Eduction Diploma infos ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='tbltertiaryeducationawards',
            name='tertiaryInfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='TblAwards_TertiaryInfo', to='education_info.tbl_education_tertiaryeducationinfos'),
        ),
    ]
