# Generated by Django 4.1.5 on 2023-02-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_info', '0002_tbl_education_tertiaryeducationinfos_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblcourses',
            options={'verbose_name': '8. TBL_COURSES', 'verbose_name_plural': '8. TBL_COURSES'},
        ),
        migrations.AlterModelOptions(
            name='tblinstitutioncourse',
            options={'verbose_name': '10: Institution Course', 'verbose_name_plural': '10: Institution Course'},
        ),
        migrations.AlterModelOptions(
            name='tbltertiaryeducationawards',
            options={'verbose_name': '9. Tertiary Education Award', 'verbose_name_plural': '9. Tertiary Education Award'},
        ),
        migrations.AlterField(
            model_name='tbl_education_institution',
            name='instituteCode',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AlterModelTable(
            name='tbl_education_applicantattendedschool',
            table='tbl_application_secondary_schools',
        ),
        migrations.AlterModelTable(
            name='tbl_education_diplomainfos',
            table='tbl_application_diploma_details',
        ),
        migrations.AlterModelTable(
            name='tbl_education_formfourinfos',
            table='tbl_application_form_four_details',
        ),
        migrations.AlterModelTable(
            name='tbl_education_formsixinfos',
            table='tbl_application_form_six_details',
        ),
        migrations.AlterModelTable(
            name='tbl_education_institution',
            table='tbl_diploma_institutions',
        ),
        migrations.AlterModelTable(
            name='tbl_education_tertiaryeducationinfos',
            table='tbl_tertiary_education',
        ),
        migrations.AlterModelTable(
            name='tbl_educationinfo',
            table='tbl_application_education_info',
        ),
        migrations.AlterModelTable(
            name='tblcourses',
            table='tbl_courses',
        ),
        migrations.AlterModelTable(
            name='tblinstitutioncourse',
            table='tbl_institutioncourses',
        ),
        migrations.AlterModelTable(
            name='tbltertiaryeducationawards',
            table='tbl_tertiary_education_awards',
        ),
    ]
