# Generated by Django 4.1.5 on 2023-02-28 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education_info', '0002_tbleducationformsixinfos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TblDiplomaDetails',
        ),
    ]
