# Generated by Django 4.1.5 on 2023-02-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_info', '0002_delete_tblinstitutioncourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institutions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('institutionName', models.CharField(db_column='institution_name', max_length=100)),
                ('institutionCode', models.CharField(db_column='institution_code', max_length=100)),
                ('geoLocated', models.BooleanField(blank=True, db_column='geo_located', default=False, null=True)),
                ('active', models.CharField(db_column='active', max_length=100)),
            ],
            options={
                'db_table': 'tbl_institutions',
                'managed': False,
            },
        ),
    ]
