# Generated by Django 4.1.5 on 2023-01-24 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education_info', '0003_alter_tbl_app_applicantattendedschool_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbl_formfourinfos',
            options={'ordering': ['-created_at'], 'verbose_name': '4:TBL Eduction Form four infos ', 'verbose_name_plural': '4:TBL Eduction Form four infos '},
        ),
        migrations.AlterModelOptions(
            name='tbl_formsixinfos',
            options={'ordering': ['-created_at'], 'verbose_name': '5:TBL Eduction Form Six infos ', 'verbose_name_plural': '5:TBL Eduction Form Six infos '},
        ),
        migrations.AlterModelOptions(
            name='tbl_tertiaryeducationinfos',
            options={'ordering': ['-created_at'], 'verbose_name': '7:TBL Eduction Diploma infos ', 'verbose_name_plural': '7:TBL Eduction Diploma infos '},
        ),
    ]
