# Generated by Django 4.1.5 on 2023-02-21 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicantProfile', '0002_rename_tbl_app_profile_tblappprofile'),
        ('education_info', '0004_alter_tbl_education_tertiaryeducationinfos_admittedinstitute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbltertiaryeducationawards',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='TblAwardsInstitution', to='education_info.institutions'),
        ),
        migrations.AlterField(
            model_name='tbltertiaryeducationawards',
            name='tertiaryInfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='TblAwards_TertiaryInfo', to='applicantProfile.tblappprofile'),
        ),
    ]
