# Generated by Django 4.1.5 on 2023-02-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_info', '0004_tbldiplomadetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbldiplomadetails',
            name='gpa',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
