# Generated by Django 4.1.5 on 2023-01-24 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans_application', '0029_delete_tbl_app_applicantattendedschool'),
        ('education_info', '0004_alter_tbl_formfourinfos_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TBL_App_ApplicantAttendedSchool',
            new_name='TBL_Education_ApplicantAttendedSchool',
        ),
        migrations.RenameModel(
            old_name='TBL_DiplomaInfos',
            new_name='TBL_Education_DiplomaInfos',
        ),
        migrations.RenameModel(
            old_name='TBL_FormFourInfos',
            new_name='TBL_Education_FormFourInfos',
        ),
        migrations.RenameModel(
            old_name='TBL_FormSixInfos',
            new_name='TBL_Education_FormSixInfos',
        ),
        migrations.RenameModel(
            old_name='TBL_TertiaryEducationInfos',
            new_name='TBL_Education_TertiaryEducationInfos',
        ),
    ]
