# Generated by Django 4.1.5 on 2023-02-20 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicantProfile', '0001_initial'),
        ('education_info', '0004_tbl_education_diplomainfos_app_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_education_diplomainfos',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ed_diploma_info_tbl_app_applicant', to='applicantProfile.tbl_app_profile'),
        ),
        migrations.AlterField(
            model_name='tbl_education_formfourinfos',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ed_form4_info_tbl_app_applicant', to='applicantProfile.tbl_app_profile'),
        ),
        migrations.AlterField(
            model_name='tbl_education_formsixinfos',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ed_form6_info_tbl_app_applicant', to='applicantProfile.tbl_app_profile'),
        ),
        migrations.AlterField(
            model_name='tbl_education_tertiaryeducationinfos',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ed_te_info_tbl_app_applicant', to='applicantProfile.tbl_app_profile'),
        ),
        migrations.AlterField(
            model_name='tbl_educationinfo',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ed_tbl_app_applicant', to='applicantProfile.tbl_app_profile'),
        ),
    ]
