# Generated by Django 4.1.5 on 2023-01-24 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education_info', '0005_rename_tbl_app_applicantattendedschool_tbl_education_applicantattendedschool_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbl_education_diplomainfos',
            options={'ordering': ['-created_at'], 'verbose_name': '6:TBL Eduction Diploma infos ', 'verbose_name_plural': '6:TBL Eduction Diploma infos '},
        ),
    ]
