# Generated by Django 4.1.5 on 2023-02-21 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education_info', '0005_alter_tbltertiaryeducationawards_institution_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbltertiaryeducationawards',
            old_name='tertiaryInfo',
            new_name='applicant',
        ),
    ]
