# Generated by Django 4.1.5 on 2023-01-24 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education_info', '0006_alter_tbl_education_diplomainfos_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbl_education_applicantattendedschool',
            options={'ordering': ['-created_at'], 'verbose_name': '2: TBL Education Applicant Attended Schools', 'verbose_name_plural': '2: TBL Education Applicant Attended Schools'},
        ),
        migrations.AlterModelOptions(
            name='tbl_education_diplomainfos',
            options={'ordering': ['-created_at'], 'verbose_name': '5:TBL Eduction Diploma infos ', 'verbose_name_plural': '5:TBL Eduction Diploma infos '},
        ),
        migrations.AlterModelOptions(
            name='tbl_education_formfourinfos',
            options={'ordering': ['-created_at'], 'verbose_name': '3: TBL Eduction Form four infos ', 'verbose_name_plural': '3: TBL Eduction Form four infos '},
        ),
        migrations.AlterModelOptions(
            name='tbl_education_formsixinfos',
            options={'ordering': ['-created_at'], 'verbose_name': '4:TBL Eduction Form Six infos ', 'verbose_name_plural': '4:TBL Eduction Form Six infos '},
        ),
        migrations.AlterModelOptions(
            name='tbl_education_tertiaryeducationinfos',
            options={'ordering': ['-created_at'], 'verbose_name': '6:TBL Eduction Diploma infos ', 'verbose_name_plural': '6:TBL Eduction Diploma infos '},
        ),
    ]
