# Generated by Django 4.1.5 on 2023-03-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_info', '0006_tblsponsordetails_app_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_education_tertiaryeducationinfos',
            name='admittedDegreeCategory',
            field=models.CharField(choices=[(0, 'MASTER'), (1, 'BACHELOR')], default=0, max_length=15),
        ),
    ]
