# Generated by Django 4.1.5 on 2023-02-22 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education_info', '0006_rename_tertiaryinfo_tbltertiaryeducationawards_applicant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbltertiaryeducationawards',
            name='awardCategory',
        ),
    ]
