# Generated by Django 4.1.5 on 2023-02-22 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education_info', '0007_remove_tbltertiaryeducationawards_awardcategory'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tbltertiaryeducationawards',
            table='tbl_tertiary_education_bachelor_awards',
        ),
    ]
