# Generated by Django 4.1.5 on 2023-03-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_info', '0007_alter_tbl_education_tertiaryeducationinfos_admitteddegreecategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbl_education_tertiaryeducationinfos',
            options={'ordering': ['-created_at'], 'verbose_name': '10. TBL Tertiary Education infos', 'verbose_name_plural': '10. TBL Tertiary Education infos'},
        ),
        migrations.AlterModelOptions(
            name='tbldiplomadetails',
            options={'ordering': ['-created_at'], 'verbose_name': '9.TBL Eduction Diploma infos ', 'verbose_name_plural': '9.TBL Eduction Diploma infos '},
        ),
        migrations.AlterField(
            model_name='tbleducationformsixinfos',
            name='f6index_no',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
