# Generated by Django 4.1.5 on 2023-01-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_info', '0007_alter_tbl_education_applicantattendedschool_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TBL_Education_institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_type', models.CharField(choices=[('DIPLOMA', 'DIPLOMA'), ('HIGH_LEVEL_EDUCATION', 'HIGH LEVEL EDUCTION')], max_length=20, null=True)),
                ('institutite_name', models.CharField(max_length=30, null=True)),
            ],
            options={
                'verbose_name': '7: TBL Eduction Institute',
                'verbose_name_plural': '7: TBL Eduction Institute',
            },
        ),
    ]
