# Generated by Django 4.1.5 on 2023-03-07 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education_info', '0008_alter_tbl_education_tertiaryeducationinfos_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblsponsordetails',
            old_name='sponsor_contact_person_phone_nunber',
            new_name='sponsor_contact_person_phone_number',
        ),
    ]
