# Generated by Django 4.1.5 on 2023-02-22 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicantProfile', '0002_rename_tbl_app_profile_tblappprofile'),
        ('education_info', '0008_alter_tbltertiaryeducationawards_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TblTertiaryEducationAwards',
            new_name='TblTertiaryEducationBachelorAwards',
        ),
    ]
