# Generated by Django 4.1.5 on 2023-03-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_info', '0009_rename_sponsor_contact_person_phone_nunber_tblsponsordetails_sponsor_contact_person_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblsponsordetails',
            name='sponsored_ed_type',
            field=models.IntegerField(choices=[(0, 'POST fORM fOUR SPONSORSHIP'), (1, 'fORM fOUR SPONSORSHIP')], null=True),
        ),
    ]
