# Generated by Django 4.1.5 on 2023-01-24 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education_info', '0009_alter_tbl_education_tertiaryeducationinfos_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbl_education_tertiaryeducationinfos',
            options={'ordering': ['-created_at'], 'verbose_name': '6:TBL Tertiary Education infos', 'verbose_name_plural': '6:TBL Tertiary Education infos'},
        ),
    ]
