# Generated by Django 4.1.5 on 2023-02-22 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicantProfile', '0002_rename_tbl_app_profile_tblappprofile'),
        ('education_info', '0009_rename_tbltertiaryeducationawards_tbltertiaryeducationbachelorawards'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbltertiaryeducationbachelorawards',
            options={'verbose_name': '9. Tertiary Education Bachelor Award', 'verbose_name_plural': '9. Tertiary Education Bachelor Award'},
        ),
        migrations.CreateModel(
            name='TblTertiaryEducationMasterAward',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('master_award', models.CharField(max_length=50)),
                ('regNo', models.CharField(max_length=40)),
                ('entryYear', models.IntegerField()),
                ('graduateYear', models.IntegerField()),
                ('gpa', models.FloatField()),
                ('app_year', models.CharField(max_length=4, null=True)),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='TblMasterAwards_Applicant', to='applicantProfile.tblappprofile')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='TblMasterAwardsInstitution', to='education_info.institutions')),
            ],
            options={
                'verbose_name': '10. Master Awards',
                'verbose_name_plural': '10. Master Awards',
                'db_table': 'tbl_tertiary_education_master_awards',
            },
        ),
    ]
