# Generated by Django 4.1.5 on 2023-02-01 09:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('education_info', '0010_alter_tbl_education_tertiaryeducationinfos_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=50)),
                ('courseCode', models.CharField(max_length=30)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='tbl_education_institution',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tbl_education_institution',
            name='instituteCode',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='tbl_education_institution',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tbl_education_tertiaryeducationinfos',
            name='admittedDegreeCategory',
            field=models.CharField(default='Master', max_length=15),
        ),
        migrations.AddField(
            model_name='tbl_education_tertiaryeducationinfos',
            name='admittedInstitute',
            field=models.ForeignKey(default='N', on_delete=django.db.models.deletion.DO_NOTHING, to='education_info.tbl_education_institution'),
        ),
        migrations.AddField(
            model_name='tbl_education_tertiaryeducationinfos',
            name='applicationYear',
            field=models.IntegerField(default='2023'),
        ),
        migrations.CreateModel(
            name='TblTertiaryEducationAwards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award', models.CharField(max_length=50)),
                ('regno', models.CharField(max_length=40)),
                ('entryYear', models.IntegerField()),
                ('graduateYear', models.IntegerField()),
                ('awardCategory', models.CharField(max_length=20)),
                ('gpa', models.FloatField()),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='TblAwardsInstitution', to='education_info.tbl_education_institution')),
                ('tertiaryInfo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='TblAwards_TertiaryInfo', to='education_info.tbl_education_tertiaryeducationinfos')),
            ],
        ),
        migrations.CreateModel(
            name='TblInstitutionCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='education_info.tblcourses')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='education_info.tbl_education_institution')),
            ],
        ),
        migrations.AddField(
            model_name='tbl_education_tertiaryeducationinfos',
            name='admittedCourse',
            field=models.ForeignKey(default='N', on_delete=django.db.models.deletion.DO_NOTHING, to='education_info.tblcourses'),
        ),
    ]
