# Generated by Django 4.1.5 on 2023-03-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_info', '0010_alter_tblsponsordetails_sponsored_ed_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblsponsordetails',
            name='sponsored_ed_type',
            field=models.IntegerField(choices=[(0, 'POST fORM fOUR SPONSORSHIP'), (1, 'FORM fOUR SPONSORSHIP')], null=True),
        ),
    ]
