# Generated by Django 4.1.5 on 2023-02-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_info', '0010_alter_tbltertiaryeducationbachelorawards_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_education_tertiaryeducationinfos',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
    ]
