# Generated by Django 4.1.5 on 2023-02-01 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education_info', '0011_tblcourses_tbl_education_institution_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_education_tertiaryeducationinfos',
            name='admittedCourse',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='education_info.tblcourses'),
        ),
        migrations.AlterField(
            model_name='tbl_education_tertiaryeducationinfos',
            name='admittedInstitute',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='education_info.tbl_education_institution'),
        ),
    ]
