# Generated by Django 4.1.5 on 2023-03-08 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_info', '0011_alter_tblsponsordetails_sponsored_ed_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_education_tertiaryeducationinfos',
            name='admittedDegreeCategory',
            field=models.CharField(choices=[('master', 'MASTER'), ('bachelor', 'BACHELOR')], default=0, max_length=15),
        ),
    ]
