# Generated by Django 4.1.5 on 2023-01-18 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TBL_App_ApplicantDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("f4_indexno", models.CharField(max_length=30, null=True)),
                ("sur_name", models.CharField(max_length=20)),
                ("middle_name", models.CharField(max_length=20)),
                (
                    "sex",
                    models.CharField(
                        choices=[("MALE", "Male"), ("FEMALE", "Female")], max_length=20
                    ),
                ),
                ("phonenumber", models.CharField(max_length=15)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name_plural": "TBL App Applicant Details",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TBL_App_Applicantion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("confirmed", models.BooleanField(default=False)),
                (
                    "applicant_details",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="tbl_app_applicant_details",
                        to="loans_application.tbl_app_applicantdetails",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "TBL App Applicants",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TBL_App_Categories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=20, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name_plural": "TBL App  Applicants Categories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TBL_App_NECTADetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index_no", models.CharField(max_length=16, unique=True)),
                (
                    "education_level",
                    models.CharField(
                        choices=[("FORM_4", "FORM FOUR"), ("FORM_6", "FORM SIX")],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=16)),
                ("middle_name", models.CharField(blank=True, max_length=16)),
                ("sur_name", models.CharField(blank=True, max_length=16)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name_plural": "TBL App Applicants NECTA User Details",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TBL_App_NoneNECTADetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index_no", models.CharField(max_length=16, unique=True)),
                ("original_no", models.CharField(max_length=30)),
                ("first_name", models.CharField(max_length=16)),
                ("middle_name", models.CharField(max_length=16)),
                ("app_year", models.CharField(max_length=16)),
                ("sur_name", models.CharField(max_length=16)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("changed_necta", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "TBL App Applicants None NECTA User Details",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TBL_App_PaymentDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pay_status",
                    models.CharField(
                        choices=[(0, "not Paid"), (1, "Paid")], default=0, max_length=20
                    ),
                ),
                ("control_number", models.CharField(max_length=30)),
                ("reference", models.CharField(max_length=30)),
                ("paid_when", models.DateTimeField()),
                ("used_by", models.CharField(max_length=16, null=True)),
                ("used_when", models.DateTimeField(max_length=16)),
                (
                    "used_status",
                    models.CharField(
                        choices=[(0, "No used"), (1, "used")], max_length=16
                    ),
                ),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "applicant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="tbl_app_applicant",
                        to="loans_application.tbl_app_applicantion",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "TBL App Payment Details",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="tbl_app_applicantion",
            name="application_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="tbl_app_applicant_category",
                to="loans_application.tbl_app_categories",
            ),
        ),
        migrations.AddField(
            model_name="tbl_app_applicantdetails",
            name="necta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="tbl_app_necta_applicant",
                to="loans_application.tbl_app_nectadetails",
            ),
        ),
        migrations.AddField(
            model_name="tbl_app_applicantdetails",
            name="none_necta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="tbl_none_app_necta_applicant",
                to="loans_application.tbl_app_nonenectadetails",
            ),
        ),
        migrations.AddField(
            model_name="tbl_app_applicantdetails",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="tbl_app_applicant",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
