# Generated by Django 4.1.5 on 2023-01-18 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans_application", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tbl_app_paymentdetails",
            name="pay_status",
            field=models.CharField(
                choices=[("no_paid", "Not Paid"), ("paid", "Paid")],
                default=0,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="tbl_app_paymentdetails",
            name="used_status",
            field=models.CharField(
                choices=[("not_used", "No used"), ("useed", "used")], max_length=16
            ),
        ),
    ]
