# Generated by Django 4.1.5 on 2023-01-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans_application", "0002_alter_tbl_app_paymentdetails_pay_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tbl_app_nectadetails",
            name="app_year",
            field=models.CharField(default=233, max_length=16),
            preserve_default=False,
        ),
    ]
