# Generated by Django 4.1.5 on 2023-01-18 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("loans_application", "0003_tbl_app_nectadetails_app_year"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tbl_app_paymentdetails",
            old_name="pay_status",
            new_name="payment_status",
        ),
    ]
