# Generated by Django 4.1.5 on 2023-01-18 13:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        (
            "loans_application",
            "0004_rename_pay_status_tbl_app_paymentdetails_payment_status",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TBL_App_InitialApplicantCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=12, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name_plural": "TBL App InitialApplicantCategory",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveField(
            model_name="tbl_app_applicantdetails",
            name="necta",
        ),
        migrations.RemoveField(
            model_name="tbl_app_applicantdetails",
            name="none_necta",
        ),
    ]
