# Generated by Django 4.1.5 on 2023-01-18 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("loans_application", "0005_tbl_app_initialapplicantcategory_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tbl_app_initialapplicantcategory",
            name="name",
        ),
        migrations.AddField(
            model_name="tbl_app_applicantdetails",
            name="applicant_categories",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="tbl_app_initial_applicant_category",
                to="loans_application.tbl_app_initialapplicantcategory",
            ),
        ),
        migrations.AddField(
            model_name="tbl_app_initialapplicantcategory",
            name="necta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="tbl_app_necta_applicant",
                to="loans_application.tbl_app_nectadetails",
            ),
        ),
        migrations.AddField(
            model_name="tbl_app_initialapplicantcategory",
            name="none_necta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="tbl_none_app_necta_applicant",
                to="loans_application.tbl_app_nonenectadetails",
            ),
        ),
    ]
