# Generated by Django 4.1.5 on 2023-01-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans_application", "0007_remove_tbl_app_applicantdetails_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="tbl_app_nectadetails",
            name="axam_year",
            field=models.CharField(default=2000, max_length=16),
            preserve_default=False,
        ),
    ]
