# Generated by Django 4.1.5 on 2023-01-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans_application", "0008_tbl_app_nectadetails_axam_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tbl_app_nectadetails",
            name="app_year",
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="tbl_app_nectadetails",
            name="axam_year",
            field=models.CharField(max_length=16, null=True),
        ),
    ]
