# Generated by Django 4.1.5 on 2023-01-18 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("loans_application", "0009_alter_tbl_app_nectadetails_app_year_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tbl_app_nectadetails",
            old_name="axam_year",
            new_name="exam_year",
        ),
    ]
