# Generated by Django 4.1.5 on 2023-01-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans_application", "0010_rename_axam_year_tbl_app_nectadetails_exam_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="tbl_app_nonenectadetails",
            name="exam_year",
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="tbl_app_nonenectadetails",
            name="app_year",
            field=models.CharField(max_length=16, null=True),
        ),
    ]
