# Generated by Django 4.1.5 on 2023-01-18 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans_application", "0012_tbl_app_nectadetails_last_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tbl_app_applicantdetails",
            name="sex",
        ),
        migrations.AddField(
            model_name="tbl_app_nectadetails",
            name="sex",
            field=models.CharField(
                choices=[("MALE", "Male"), ("FEMALE", "Female")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tbl_app_nonenectadetails",
            name="sex",
            field=models.CharField(
                choices=[("MALE", "Male"), ("FEMALE", "Female")],
                max_length=20,
                null=True,
            ),
        ),
    ]
