# Generated by Django 4.1.5 on 2023-01-19 06:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("loans_application", "0013_remove_tbl_app_applicantdetails_sex_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TBL_App_ApplicantAttendedSchool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "center_number",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("center_name", models.CharField(blank=True, max_length=10, null=True)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "necta_applicants",
                    models.ManyToManyField(to="loans_application.tbl_app_nectadetails"),
                ),
            ],
            options={
                "verbose_name_plural": "TBL App Applicant Attended Schools",
                "ordering": ["-created_at"],
            },
        ),
    ]
