# Generated by Django 4.1.5 on 2023-01-19 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "loans_application",
            "0015_alter_tbl_app_applicantattendedschool_center_number",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TBL_App_Applicantion",
            new_name="TBL_App_Applicant",
        ),
    ]
