# Generated by Django 4.1.5 on 2023-01-19 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("loans_application", "0018_alter_tbl_app_paymentdetails_used_status"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TBL_App_InitialApplicantCategory",
            new_name="TBL_App_ApplicantType",
        ),
        migrations.AlterModelOptions(
            name="tbl_app_applicanttype",
            options={
                "ordering": ["-created_at"],
                "verbose_name_plural": "TBL App ApplicantTyp",
            },
        ),
    ]
