# Generated by Django 4.1.5 on 2023-01-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "loans_application",
            "0019_rename_tbl_app_initialapplicantcategory_tbl_app_applicanttype_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tbl_app_applicanttype",
            options={
                "ordering": ["-created_at"],
                "verbose_name_plural": "TBL App ApplicantType",
            },
        ),
        migrations.AddField(
            model_name="tbl_app_applicantdetails",
            name="email",
            field=models.EmailField(blank=True, max_length=30, null=True),
        ),
    ]
