# Generated by Django 4.1.5 on 2023-01-20 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("loans_application", "0020_alter_tbl_app_applicanttype_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tbl_app_applicantdetails",
            old_name="applicant_categories",
            new_name="applicant_type",
        ),
    ]
