# Generated by Django 4.1.5 on 2023-01-20 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "loans_application",
            "0021_rename_applicant_categories_tbl_app_applicantdetails_applicant_type",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="tbl_app_applicantdetails",
            name="applicant_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="tbl_app_initial_applicant_type",
                to="loans_application.tbl_app_applicanttype",
            ),
        ),
        migrations.AlterField(
            model_name="tbl_app_nectadetails",
            name="index_no",
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="tbl_app_nonenectadetails",
            name="index_no",
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
