# Generated by Django 4.1.5 on 2023-01-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "loans_application",
            "0022_alter_tbl_app_applicantdetails_applicant_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="tbl_app_nonenectadetails",
            name="index_no",
            field=models.CharField(
                blank=True, editable=False, max_length=16, null=True, unique=True
            ),
        ),
    ]
