# Generated by Django 4.1.5 on 2023-01-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans_application", "0023_alter_tbl_app_nonenectadetails_index_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tbl_app_nectadetails",
            name="index_no",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
