# Generated by Django 4.1.5 on 2023-01-20 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("loans_application", "0024_alter_tbl_app_nectadetails_index_no"),
    ]

    operations = []
