# Generated by Django 4.1.5 on 2023-01-24 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans_application', '0025_auto_20230120_1724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbl_app_applicant',
            options={'ordering': ['-created_at'], 'verbose_name': 'TBL App Payment Details', 'verbose_name_plural': 'TBL App Payment Details'},
        ),
        migrations.AlterModelOptions(
            name='tbl_app_applicantattendedschool',
            options={'ordering': ['-created_at'], 'verbose_name': '6:TBL App Applicant Attended Schools', 'verbose_name_plural': '6:TBL App Applicant Attended Schools'},
        ),
        migrations.AlterModelOptions(
            name='tbl_app_applicantdetails',
            options={'ordering': ['-created_at'], 'verbose_name': '3: TBL App Applicant Details', 'verbose_name_plural': '3: TBL App Applicant Details'},
        ),
        migrations.AlterModelOptions(
            name='tbl_app_applicanttype',
            options={'ordering': ['-created_at'], 'verbose_name': '2: TBL App ApplicantType', 'verbose_name_plural': '2: TBL App ApplicantType'},
        ),
        migrations.AlterModelOptions(
            name='tbl_app_categories',
            options={'ordering': ['-created_at'], 'verbose_name': '4: TBL App  Applicants Categories', 'verbose_name_plural': '4: TBL App  Applicants Categories'},
        ),
        migrations.AlterModelOptions(
            name='tbl_app_nectadetails',
            options={'ordering': ['-created_at'], 'verbose_name': '1.0: TBL App Applicants NECTA User Details', 'verbose_name_plural': '1.0: TBL App Applicants NECTA User Details'},
        ),
        migrations.AlterModelOptions(
            name='tbl_app_nonenectadetails',
            options={'ordering': ['-created_at'], 'verbose_name': '1.1: TBL App Applicants None NECTA User Details', 'verbose_name_plural': '1.1: TBL App Applicants None NECTA User Details'},
        ),
        migrations.AlterModelOptions(
            name='tbl_app_paymentdetails',
            options={'ordering': ['-created_at'], 'verbose_name': '6: TBL App Payment Details', 'verbose_name_plural': '6: TBL App Payment Details'},
        ),
    ]
