# Generated by Django 4.1.5 on 2023-01-24 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans_application', '0026_alter_tbl_app_applicant_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbl_app_applicantattendedschool',
            options={'ordering': ['-created_at'], 'verbose_name': '7:TBL App Applicant Attended Schools', 'verbose_name_plural': '7:TBL App Applicant Attended Schools'},
        ),
    ]
