# Generated by Django 4.1.5 on 2023-01-24 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans_application', '0027_alter_tbl_app_applicantattendedschool_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbl_app_applicant',
            options={'ordering': ['-created_at'], 'verbose_name': '5: TBL Applicant Details', 'verbose_name_plural': '5: TBL Applicant Details'},
        ),
    ]
