# Generated by Django 4.1.5 on 2023-01-25 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans_application', '0029_delete_tbl_app_applicantattendedschool'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbl_app_applicant',
            options={'ordering': ['-created_at'], 'verbose_name': '5: TBL Applicant Conso Tbl', 'verbose_name_plural': '5: TBL Applicant Conso Tbl'},
        ),
    ]
