# Generated by Django 4.1.5 on 2023-01-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans_application', '0031_alter_tbl_app_paymentdetails_paid_when'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_app_paymentdetails',
            name='control_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_app_paymentdetails',
            name='paid_when',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_app_paymentdetails',
            name='payment_status',
            field=models.CharField(choices=[('no_paid', 'Not Paid'), ('paid', 'Paid')], default=0, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_app_paymentdetails',
            name='reference',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_app_paymentdetails',
            name='used_by',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_app_paymentdetails',
            name='used_status',
            field=models.CharField(blank=True, choices=[('not_used', 'No used'), ('used', 'used')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_app_paymentdetails',
            name='used_when',
            field=models.DateTimeField(blank=True, max_length=16, null=True),
        ),
    ]
