# Generated by Django 4.1.5 on 2023-01-26 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans_application', '0032_alter_tbl_app_paymentdetails_control_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_app_paymentdetails',
            name='payment_status',
            field=models.CharField(choices=[('no_paid', 'Not Paid'), ('paid', 'Paid')], default='no_paid', max_length=20, null=True),
        ),
    ]
