# Generated by Django 4.1.5 on 2023-01-27 06:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loans_application', '0034_remove_tbl_app_nectadetails_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_app_nectadetails',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tbl_app_nonenectadetails',
            name='user',
        ),
        migrations.AddField(
            model_name='tbl_app_nectadetails',
            name='first_name',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='tbl_app_nectadetails',
            name='last_name',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='tbl_app_nonenectadetails',
            name='first_name',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='tbl_app_nonenectadetails',
            name='last_name',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_app_nonenectadetails',
            name='changed_necta',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_app_nonenectadetails',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_app_nonenectadetails',
            name='middle_name',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_app_nonenectadetails',
            name='original_no',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_app_nonenectadetails',
            name='sur_name',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_app_nonenectadetails',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
