# Generated by Django 4.1.5 on 2023-02-06 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans_application', '0038_alter_tbl_app_paymentdetails_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_app_paymentdetails',
            name='amount_paid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
