# Generated by Django 4.1.5 on 2023-02-06 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans_application', '0039_tbl_app_paymentdetails_amount_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='TBL_App_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(default=False)),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tbl_app_applicant_profile_set', to='loans_application.tbl_app_applicant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_profile_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '7: Applicant Profile',
                'verbose_name_plural': '7: Applicant Profile',
            },
        ),
    ]
