# Generated by Django 4.1.5 on 2023-02-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans_application', '0040_tbl_app_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_app_paymentdetails',
            name='payment_status',
            field=models.IntegerField(choices=[(0, 'Not Paid'), (1, 'Paid')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_app_paymentdetails',
            name='used_status',
            field=models.IntegerField(blank=True, choices=[(0, 'Not used'), (1, 'Used')], default=0, null=True),
        ),
    ]
