# Generated by Django 4.1.5 on 2023-02-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans_application', '0041_alter_tbl_app_paymentdetails_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_app_applicant',
            name='confirmed',
        ),
        migrations.AddField(
            model_name='tbl_app_profile',
            name='secrete_answer',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tbl_app_profile',
            name='secrete_question',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
