# Generated by Django 4.1.5 on 2023-02-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans_application', '0042_remove_tbl_app_applicant_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_app_profile',
            name='secrete_answer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_app_profile',
            name='secrete_question',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
