# Generated by Django 4.1.5 on 2023-02-07 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans_application', '0044_rename_secrete_answer_tbl_app_profile_secret_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_app_profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_profile_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
