# Generated by Django 4.1.5 on 2023-02-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans_application', '0045_alter_tbl_app_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_app_nonenectadetails',
            name='original_no',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
