# Generated by Django 4.1.5 on 2023-02-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans_application', '0048_alter_tbl_app_applicant_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_app_applicant',
            name='app_year',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='tbl_app_applicantdetails',
            name='appYear',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='tbl_app_paymentdetails',
            name='app_year',
            field=models.CharField(max_length=4, null=True),
        ),
        # migrations.DeleteModel(
        #     name='TBL_App_Profile',
        # ),
    ]
