# Generated by Django 4.1.5 on 2023-02-21 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans_application', '0049_tbl_app_applicant_app_year_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TBL_App_Profile',
        ),
    ]
