# Generated by Django 4.1.5 on 2023-01-24 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import guarantordetails.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demographics', '0001_initial'),
        ('loans_application', '0029_delete_tbl_app_applicantattendedschool'),
    ]

    operations = [
        migrations.CreateModel(
            name='TBL_GuarantorDetailsLUG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sur_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30, null=True)),
                ('sex', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10, null=True)),
                ('postaladdress', models.CharField(max_length=10, null=True)),
                ('mobile', models.CharField(max_length=10, null=True)),
                ('email', models.CharField(max_length=10, null=True)),
                ('ward', models.CharField(max_length=10, null=True)),
                ('village', models.CharField(max_length=10, null=True)),
                ('idcardnumber', models.CharField(max_length=10, null=True)),
                ('cardtype', models.CharField(max_length=10, null=True)),
                ('photo', models.FileField(max_length=10, null=True, upload_to=guarantordetails.models.TBL_GuarantorDetailsLUG.image_upload_to)),
                ('confirm', models.CharField(max_length=10, null=True)),
                ('photoverified', models.BooleanField(default=False)),
                ('referenceId', models.CharField(max_length=10, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='guarantor_tbl_app_applicant', to='loans_application.tbl_app_applicant')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='guarantor_district', to='demographics.tbl_demo_region')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='guarantor_region', to='demographics.tbl_demo_region')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_guarantor_details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '6: Guarant details LUG',
                'verbose_name_plural': '6: Guarant details LUG',
                'ordering': ['-created_at'],
            },
        ),
    ]
