# Generated by Django 4.1.5 on 2023-02-17 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guarantordetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tbl_guarantordetailslug',
            table='tbl_application_guarantor_details',
        ),
        migrations.AlterModelTable(
            name='tbl_guarantordetailspgd',
            table='tbl_application_demographics_details_PGD',
        ),
    ]
