# Generated by Django 4.1.5 on 2023-02-19 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicantProfile', '0001_initial'),
        ('guarantordetails', '0002_tbl_guarantordetailslug_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_guarantordetailslug',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='guarantor_tbl_app_applicant', to='applicantProfile.tbl_app_profile'),
        ),
        migrations.AlterField(
            model_name='tbl_guarantordetailspgd',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='guarantor_PGD_tbl_app_applicant', to='applicantProfile.tbl_app_profile'),
        ),
    ]
