# Generated by Django 4.1.5 on 2023-01-24 13:20

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('guarantordetails', '0003_alter_tbl_guarantordetailslug_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_guarantordetailslug',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='tbl_guarantordetailspgd',
            name='telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
    ]
