# Generated by Django 4.1.5 on 2023-01-24 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guarantordetails', '0005_tbl_guarantordetailspgd_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_guarantordetailslug',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tbl_guarantordetailspgd',
            name='user',
        ),
    ]
