# Generated by Django 4.1.5 on 2023-02-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guarantordetails', '0006_remove_tbl_guarantordetailslug_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_guarantordetailslug',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tbl_guarantordetailspgd',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
