# Generated by Django 4.1.5 on 2023-02-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserApplicationStateManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_id', models.IntegerField(null=True)),
                ('proocess_name', models.IntegerField(choices=[(1, 'APPLLICATION_FEE_AND_PAYMENTS'), (2, 'SELF_REGISTRATION'), (3, 'APPLICATION_CATEGORY'), (4, 'APPLICANT_BASIC_INFO'), (5, 'DEMOGRAPHICS_INFO'), (6, 'PRELIMINARY_INFO'), (7, 'EDUCATION_INFO'), (8, 'GUARANTOR_INFO')])),
                ('menu_state', models.CharField(choices=[('DONE', 'DONE'), ('IN_PROGRESS', 'iN PROGRESS'), ('nOT_STARTED', 'NOT STARTED')], max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='olamsconfigurations',
            options={'verbose_name': '1: Olams Configurations', 'verbose_name_plural': '1: Olams Configurations'},
        ),
    ]
