# Generated by Django 4.1.5 on 2023-02-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_userapplicationstatemanager_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userapplicationstatemanager',
            old_name='proocess_name',
            new_name='process_name',
        ),
        migrations.AlterField(
            model_name='userapplicationstatemanager',
            name='menu_state',
            field=models.CharField(choices=[('DONE', 'DONE'), ('IN_PROGRESS', 'IN PROGRESS'), ('nOT_STARTED', 'NOT STARTED')], max_length=20),
        ),
    ]
