# Generated by Django 4.1.5 on 2023-02-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_rename_proocess_name_userapplicationstatemanager_process_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapplicationstatemanager',
            name='menu_state',
            field=models.CharField(choices=[('DONE', 'DONE'), ('IN_PROGRESS', 'IN PROGRESS'), ('NOT_STARTED', 'NOT STARTED')], max_length=20),
        ),
    ]
