# Generated by Django 4.1.5 on 2023-02-20 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_alter_userapplicationstatemanager_menu_state'),
        ('settings', '0004_alter_userapplicationstatemanager_menu_state'),
    ]

    operations = [
    ]
