# Generated by Django 4.1.5 on 2023-02-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_merge_20230221_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapplicationstatemanager',
            name='menu_state',
            field=models.CharField(choices=[('DONE', 'DONE'), ('IN_PROGRESS', 'IN PROGRESS'), ('NOT_STARTED', 'NOT STARTED')], max_length=20),
        ),
    ]
