# Generated by Django 4.1.5 on 2023-02-23 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_merge_20230222_1035'),
        ('settings', '0006_alter_userapplicationstatemanager_menu_state'),
    ]

    operations = [
    ]
