# Generated by Django 4.1.5 on 2023-03-03 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_merge_20230222_1243'),
        ('settings', '0007_merge_20230223_1032'),
    ]

    operations = [
    ]
