# Generated by Django 4.1.5 on 2023-01-24 08:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans_application', '0025_auto_20230120_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_Demo_Disability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': '4: TBL Demo Disability',
                'verbose_name_plural': '4: TBL Demo Disability',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TBL_Demo_District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': '3: TBL Demo District',
                'verbose_name_plural': '3: TBL Demo District',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TBL_Demo_Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': '2: TBL Demo Region',
                'verbose_name_plural': '2: TBL Demo Region',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TBL_Demo_DemocileDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(null=True)),
                ('disability', models.BooleanField(default=False)),
                ('dom_postal', models.CharField(max_length=50, null=True)),
                ('dom_ward', models.CharField(max_length=50, null=True)),
                ('birth_cert_no', models.CharField(max_length=50, null=True)),
                ('cert_type_id', models.CharField(max_length=50, null=True)),
                ('nationalIdNo', models.CharField(max_length=50, null=True)),
                ('birthplace', models.CharField(max_length=50, null=True)),
                ('dom_village', models.CharField(max_length=30, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('confirm', models.BooleanField(default=False)),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='demo_tbl_app_applicant', to='loans_application.tbl_app_applicant')),
                ('distric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='demographics.tbl_demo_district')),
                ('dom_distric', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='demo_domestic_distric', to='demographics.tbl_demo_district')),
                ('dom_region', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='demo_domestic_region', to='demographics.tbl_demo_region')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='demo_tbl_demo_region', to='demographics.tbl_demo_region')),
            ],
            options={
                'verbose_name': '1: TBL Demo Democile Details',
                'verbose_name_plural': '1: TBL Demo Democile Details',
                'ordering': ['-created_at'],
            },
        ),
    ]
