# Generated by Django 4.1.5 on 2023-02-01 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demographics', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tbl_Demo_Disability',
        ),
    ]
