# Generated by Django 4.1.5 on 2023-02-27 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demographics', '0002_alter_tblregions_region_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblregions',
            name='region_id',
            field=models.AutoField(default=111, primary_key=True, serialize=False),
        ),
    ]
