# Generated by Django 4.1.5 on 2023-02-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demographics', '0002_tbldemographicsdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbldemographicsdetails',
            name='app_year',
            field=models.CharField(max_length=4),
        ),
    ]
