# Generated by Django 4.1.5 on 2023-02-19 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicantProfile', '0001_initial'),
        ('demographics', '0003_alter_tbldemographicsdetails_app_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbldemographicsdetails',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demo_tbl_app_applicant', to='applicantProfile.tbl_app_profile'),
        ),
    ]
