# Generated by Django 4.1.5 on 2023-02-22 08:26

import attachments.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applicantProfile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TBL_AttachemetsDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=attachments.models.TBL_AttachemetsDocs.image_upload_to)),
            ],
            options={
                'verbose_name': '2: TBL Attachments Docs',
                'verbose_name_plural': '2: TBL Attachments Docs',
                'db_table': 'tbl_application_attachments_docs',
            },
        ),
        migrations.CreateModel(
            name='TBL_attachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.CharField(max_length=30, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('verification', models.BooleanField(default=False)),
                ('filename', models.CharField(max_length=100, null=True)),
                ('app_year', models.CharField(max_length=4, null=True)),
                ('verifieddate', models.DateTimeField()),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('confirm', models.BooleanField(default=False)),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachment_tbl_app_applicant', to='applicantProfile.tblappprofile')),
                ('docid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='attachement_doc', to='attachments.tbl_attachemetsdocs')),
                ('verifiedby', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '1: TBL Attachments Docs',
                'verbose_name_plural': '1: TBL Attachments Docs',
                'db_table': 'tbl_application_attachments',
            },
        ),
    ]
