# Generated by Django 4.1.5 on 2023-01-24 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbl_attachments',
            options={'verbose_name': '1: TBL Attachments Docs', 'verbose_name_plural': '1: TBL Attachments Docs'},
        ),
    ]
