# Generated by Django 4.1.5 on 2023-01-24 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0002_alter_tbl_attachments_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbl_attachments',
            options={'verbose_name': '2: TBL Attachments Docs', 'verbose_name_plural': '2: TBL Attachments Docs'},
        ),
    ]
