# Generated by Django 4.1.5 on 2023-01-24 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans_application', '0029_delete_tbl_app_applicantattendedschool'),
        ('attachments', '0003_alter_tbl_attachments_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_attachments',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='attachment_tbl_app_applicant', to='loans_application.tbl_app_applicant'),
        ),
    ]
