# Generated by Django 4.1.5 on 2023-02-19 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans_application', '0048_alter_tbl_app_applicant_table_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TBL_App_Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('secret_question', models.CharField(blank=True, max_length=100, null=True)),
                ('secret_answer', models.CharField(blank=True, max_length=100, null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tbl_app_applicant_profile_set', to='loans_application.tbl_app_applicant')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_profile_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '7: Applicant Profile',
                'verbose_name_plural': '7: Applicant Profile',
                'db_table': 'tbl_applicant_profile',
            },
        ),
    ]
