# Generated by Django 4.1.5 on 2023-02-22 08:25

import applicantProfile.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans_application', '0050_delete_tbl_app_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblAppProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('secret_question', models.CharField(blank=True, max_length=100, null=True)),
                ('secret_answer', models.CharField(blank=True, max_length=100, null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tbl_app_applicant_profile_set', to='loans_application.tbl_app_applicant')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_profile_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '7: Applicant Profile',
                'verbose_name_plural': '7: Applicant Profile',
                'db_table': 'tbl_applicant_profile',
            },
        ),
        migrations.CreateModel(
            name='ApplicantPhoto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=applicantProfile.models.ApplicantPhoto.image_upload_to)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('confirm', models.BooleanField(default=False)),
                ('applicant_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tbl_app_applicant_photo_set', to='applicantProfile.tblappprofile')),
            ],
            options={
                'verbose_name': '7: Applicant Photo',
                'verbose_name_plural': '7: Applicant Photo',
                'db_table': 'tbl_applicant_photo',
            },
        ),
    ]
