# Generated by Django 4.1.5 on 2023-02-22 07:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0009_alter_tbl_attachments_applicant'),
        ('loans_application', '0050_delete_tbl_app_profile'),
        ('demographics', '0004_alter_tbldemographicsdetails_applicant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('education_info', '0001_initial'),
        ('guarantordetails', '0004_alter_tbl_guarantordetailslug_applicant_and_more'),
        ('preliminary_info', '0009_alter_tblpreliminaryinfo_applicant'),
        ('applicantProfile', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TBL_App_Profile',
            new_name='TblAppProfile',
        ),
    ]
