# Generated by Django 4.1.5 on 2023-02-22 07:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans_application', '0050_delete_tbl_app_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('education_info', '0001_initial'),
        ('applicantProfile', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TBL_App_Profile',
            new_name='TblAppProfile',
        ),
    ]
